### ISSUE TITLE
Blueprint od-spot-split contains spot and on-demand as capacity type in NodePool node-spot which might be misleading

### ISSUE THREAD

**Issue by youwalther65** [aws-samples/karpenter-blueprints#11]
For clarity we should remove on-demand as karpenter.sh/capacity-type in NodePool `od-spot` to not confuse people.
Even though documentation states , that on-demand can be used as a fallback option for spot in [What if there is no Spot capacity? Will Karpenter use On-Demand?](https://karpenter.sh/docs/faq/#what-if-there-is-no-spot-capacity-will-karpenter-use-on-demand), best practise is to diversify spot properly.
I will submit a PR for this small change as well.

**Comment by chrismld** [comment]
PR Merged, thanks Jens-Uwe :)
