### ISSUE TITLE
Please add this to the Karpenter getting started page

### ISSUE THREAD

**Issue by robertdeheer** [aws-samples/karpenter-blueprints#14]
Hello,

I would like to thank you for preparing this boilerplate Karpenter deployment in terraform. Can I suggest adding it to the Karpenter getting started page? it's a bit of a challenge to translate the bash/CloudFormation scripts into terraform. 

**https://github.com/aws-samples/karpenter-blueprints/tree/main/cluster/terraform**

Thanks,
Rob

**Comment by chrismld** [comment]
hello @robertdeheer, thanks for letting us know you find these blueprints useful. To your point, we already have the reference link here: https://karpenter.sh/docs/getting-started/. The Terraform files you find in this repo are similar to the ones we have in the EKS Blueprints repo (which is described already in the getting started guide).

**Comment by chrismld** [comment]
@robertdeheer I'm closing this issue but let me know if you were looking for something else and re-open it :)
