### ISSUE TITLE
Kubernetes Version 1.30

### ISSUE THREAD

**Issue by guilhermemilesi7** [aws-samples/karpenter-blueprints#15]
Thank you for making the Blueprints available, they are a great help.

I would like to know about using Kubernetes 1.30 and Karpenter, do I need to update it? Auxiliary material?

Thanks!

**Comment by chrismld** [comment]
hello @guilhermemilesi7, thanks for raising this issue. As @jakeskyaws said, we try to keep versions updated as much as possible, and Jake highlighted the places you could update. And +1 on having contributions from the community. However, this time won't be needed as I didn't realize I didn't push my latest changes to update the repository. Give it a try/look, the repo is now using the most recent versions of Kubernetes and Karpenter.
