### ISSUE TITLE
Another Use Case, Always having Latest AMI Running

### ISSUE THREAD

**Issue by joshkurz** [aws-samples/karpenter-blueprints#3]
Would another potential  use case be, how can a user always ensure they have the lastest AMI deployed? Even without a control panel upgrade, AMI updates happen often and it can cause heavy lifting to keep up with when a new AMI has come out and when to upgrade the nodes. Can we show how to keep a nodegroup automatically updated with latest AMI no matter if control panel was upgraded or not? This would essentially alleviate patching concerns for users and they would always have a cluster that is patched with latest AMI nodes.

**Comment by chrismld** [comment]
hey @joshkurz thanks for submitting a new use case :) ... for this one, we already talk about this in the [Update Nodes using Drift](https://github.com/aws-samples/karpenter-blueprints/tree/main/blueprints/update-nodes-with-drift#karpenter-blueprint-update-nodes-using-drift) blueprint. The scenario you're describing is what Karpenter already does: `Karpenter detects when a new AMI is released for the version of the Kubernetes cluster and drifts the existing nodes. `. Would be hard to replicate deterministically to see nodes being replaced when a new AMI is launched unless you're using custom AMIs.

**Comment by joshkurz** [comment]
Ok Awesome. TY and just wanted to confirm this. Appreciate it.
