### ISSUE TITLE
After using user to run terraform ,  the cluster can not accessed by the user.

### ISSUE THREAD

**Issue by yuew620** [aws-samples/karpenter-blueprints#8]
I set AKSK in cloud9 as a IAM user, and run the terraform following guide. 
The terraform run success.

When I run "kubectl get pods -A"
I get the error  as below
"E0408 11:11:19.589785    6069 memcache.go:265] couldn't get current server API group list: the server has asked for the client to provide credentials
error: You must be logged in to the server (the server has asked for the client to provide credentials)

When I run "kubectl get nodes -v9"
got error as below
I0408 11:11:32.495518    6129 loader.go:395] Config loaded from file:  /home/ec2-user/.kube/config
I0408 11:11:32.496096    6129 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json;g=apidiscovery.k8s.io;v=v2beta1;as=APIGroupDiscoveryList,application/json" -H "User-Agent: kubectl/v1.29.3 (linux/amd64) kuberne es/6813625" 'https://5E8F1298730CF38F687992CCEE5FE097.gr7.us-east-1.eks.amazonaws.com/api?timeout=32s'
I0408 11:11:33.139438    6129 round_trippers.go:495] HTTP Trace: DNS Lookup for 5E8F1298730CF38F687992CCEE5FE097.gr7.us-east-1.eks.amazonaws.com resolved to [{54.205.96.184 } {34.202.67.246 }]
I0408 11:11:33.140557    6129 round_trippers.go:510] HTTP Trace: Dial to tcp:54.205.96.184:443 succeed

This issue can be reproduced steadily.
Really need your help
Thanks a lot

**Comment by yuew620** [comment]
I changed to EC2, and set the AKSK.  It can be worked. 
It is  issue related to Cloud9.
Can not understand

**Comment by chrismld** [comment]
Closing this issue as it looks like it got solved
